_schema: _schema
paths:
  uploads: public/
  uploads_use_relative_path: true
  static: public
collections_config:
  pages:
    path: src/content/pages
    name: Pages
    icon: wysiwyg
    url:
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  authors:
    path: src/content/authors
    name: Authors
    icon: person
    url: /authors
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  careers:
    path: src/content/careers
    name: Careers
    icon: camera
    url: /careers
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  config:
    path: src/config
    name: Config
    icon: coffee
    disable_url: true
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  homepage:
    path: src/content/homepage
    name: Homepage
    icon: compare
    url: /
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  integrations:
    path: src/content/integrations
    name: Integrations
    icon: attractions
    url: /integrations
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/content/posts
    name: Posts
    icon: event_available
    url: /blog
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  sections:
    path: src/content/sections
    name: Sections
    icon: directions
    disable_url: true
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
