source: /src/
collections_config:
  pages:
    path: content/pages
    name: Pages
    icon: wysiwyg
    disable_url: true
  authors:
    path: content/authors
    name: Authors
    icon: person
    disable_url: true
  careers:
    path: content/careers
    name: Careers
    icon: camera
    disable_url: true
  config:
    path: config
    name: Config
    icon: coffee
    disable_url: true
  homepage:
    path: content/homepage
    name: Homepage
    icon: compare
    disable_url: true
  integrations:
    path: content/integrations
    name: Integrations
    icon: attractions
    disable_url: true
  posts:
    path: content/posts
    name: Posts
    icon: event_available
    disable_url: true
  sections:
    path: content/sections
    name: Sections
    icon: directions
    disable_url: true
paths:
  static: public
  uploads: public/uploads
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    gfm: true
